services:
  postgres:
    image: postgres:14
    container_name: paper_postgres
    restart: always
    environment:
      POSTGRES_DB: paper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/table_schema.sql:/docker-entrypoint-initdb.d/table_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: paper_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: paper_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

  cron:
    image: curlimages/curl:latest
    container_name: paper_cron
    user: root
    depends_on:
      - backend
    entrypoint: >
      sh -c "echo '0 0 * * 0 curl -X POST http://backend:8000/api/reset-weekly/' > /etc/crontabs/root
      && crond -f -d 8"


volumes:
  pgdata:
